# Generated by Django 5.1.4 on 2024-12-24 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
    ]
